import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const PASSWORD = "Dreamt2-Rotten8-Overfill6-Prissy2-Graded3"
const OS_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ3YXRjaHRvd2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6IndhdGNodG93ZXItdG9rZW4tZ2tobTQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoid2F0Y2h0b3dlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjI5ZGI5ZWZhLTE0YjQtMTFlOS04MjFlLWZhMTYzZThiODgxOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp3YXRjaHRvd2VyOndhdGNodG93ZXIifQ.FgX6P5Tf_vFOqYtJCGM6YTUDF1hUJ3ndJ-q31ypct9T8veFiW1LL5qly3rUsd-H_i9od88KtRlXTAZzrxN2C5M3OYLnhkERr2ynTW2rf6_jgderoCQMukojN7O9rX056Lyrgz5T1OCnSy4QqMKiniIKIz7tKRnodkD3447TpJW4tZz-ISEavvnNvTV24zVREtr0knE1_G3WWqsy4lFe9yqcdj9pdyoEWyZGy_wWCXgpq3aiUaah8Vg-E_wF7UU0oPyMQNDg5Jxtz68GR321NlCHKdg3WH4AKlPEvo5fCP5VId7jOSc9IDrfHi9deQFlg0cPnmvPrG91Gj9lD4dzYKg"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

       <h1>Congratulations!</h1>
  <p>You've completed the essentials of automated application deployment with GitHub Actions! 🥳</p>

      </main>
    </>
  )
}
